
export const OnlineStoreText = {
    GB: { en: "UNITED KINGDOM", ar: "المملكة المتحدة ", isoen: '', isoar:'' },
    AR: { en: "ARGENTINA", ar: "الأرجنتين", isoen: 'GLOBAL', isoar: 'عالمي' },
    AU: { en: "AUSTRALIA", ar: "أستراليا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BS: { en: "BAHAMAS", ar: "الباهاما", isoen: 'GLOBAL', isoar: 'عالمي' },
    BE: { en: "BELGIUM", ar: "بلجيكا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BR: { en: "BRAZIL", ar: "البرازيل", isoen: 'GLOBAL', isoar: 'عالمي' },
    CA: { en: "CANADA", ar: "كندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    CN: { en: "CHINA", ar: "الصين", isoen: 'GLOBAL', isoar: 'عالمي' },
    CO: { en: "COLOMBIA", ar: "كولومبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    CU: { en: "CUBA", ar: "كوبا", isoen: 'GLOBAL', isoar: 'عالمي' },
    DO: { en: "DOMINICAN REPUBLIC", ar: "جمهورية الدومينيكان", isoen: 'GLOBAL', isoar: 'عالمي' },
    EC: { en: "ECUADOR", ar: "الاكوادور", isoen: 'GLOBAL', isoar: 'عالمي' },
    SV: { en: "EL SALVADOR", ar: "السلفادور", isoen: 'GLOBAL', isoar: 'عالمي' },
    FR: { en: "FRANCE", ar: "فرنسا", isoen: 'GLOBAL', isoar: 'عالمي' },
    DE: { en: "GERMANY", ar: "ألمانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GT: { en: "GUATEMALA", ar: "جواتيمالا", isoen: 'GLOBAL', isoar: 'عالمي' },
    HT: { en: "HAITI", ar: "هايتي", isoen: 'GLOBAL', isoar: 'عالمي' },
    HN: { en: "HONDURAS", ar: "هندوراس", isoen: 'GLOBAL', isoar: 'عالمي' },
    IN: { en: "INDIA", ar: "الهند", isoen: 'GLOBAL', isoar: 'عالمي' },
    IE: { en: "IRELAND", ar: "إيرلندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    IL: { en: "ISRAEL", ar: "إسرائيل", isoen: 'GLOBAL', isoar: 'عالمي' },
    IT: { en: "ITALY", ar: "إيطاليا", isoen: 'GLOBAL', isoar: 'عالمي' },
    JP: { en: "JAPAN", ar: "اليابان", isoen: 'GLOBAL', isoar: 'عالمي' },
    KR: { en: "KOREA", ar: "كوريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    MX: { en: "MEXICO", ar: "المكسيك", isoen: 'GLOBAL', isoar: 'عالمي' },
    NL: { en: "NETHERLANDS", ar: "هولندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    PH: { en: "PHILIPPINES", ar: "فيلبيني", isoen: 'GLOBAL', isoar: 'عالمي' },
    ES: { en: "SPAIN", ar: "إسبانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SE: { en: "SWEDEN", ar: "السويد", isoen: 'GLOBAL', isoar: 'عالمي' },
    CH: { en: "SWITZERLAND", ar: "سويسرا", isoen: 'GLOBAL', isoar: 'عالمي' },
    TW: { en: "TAIWAN", ar: "تايوان", isoen: 'GLOBAL', isoar: 'عالمي' },
    VE: { en: "VENEZUELA", ar: "فنزويلا", isoen: 'GLOBAL', isoar: 'عالمي' },
    VN: { en: "VIET NAM", ar: "فيتنام", isoen: 'GLOBAL', isoar: 'عالمي' },
    AF: { en: "AFGHANISTAN", ar: "أفغانستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    AL: { en: "ALBANIA", ar: "ألبانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    DZ: { en: "ALGERIA", ar: "الجزائر", isoen: 'GLOBAL', isoar: 'عالمي' },
    AS: { en: "AMERICAN SAMOA", ar: "ساموا الأمريكية", isoen: 'GLOBAL', isoar: 'عالمي' },
    AD: { en: "ANDORRA", ar: "أندورا", isoen: 'GLOBAL', isoar: 'عالمي' },
    AO: { en: "ANGOLA", ar: "أنغولا", isoen: 'GLOBAL', isoar: 'عالمي' },
    AM: { en: "ARMENIA", ar: "أرمينيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    AT: { en: "AUSTRIA", ar: "النمسا", isoen: 'GLOBAL', isoar: 'عالمي' },
    AZ: { en: "AZERBAIJAN", ar: "أذربيجان", isoen: 'GLOBAL', isoar: 'عالمي' },
    BH: { en: "Bahrain", ar: "البحرين", isoen: 'BHR', isoar: 'البحرين' },
    BD: { en: "BANGLADESH", ar: "بنغلاديش", isoen: 'GLOBAL', isoar: 'عالمي' },
    BB: { en: "BARBADOS", ar: "بربادوس", isoen: 'GLOBAL', isoar: 'عالمي' },
    BY: { en: "BELARUS", ar: "بيلاروسيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BZ: { en: "BELIZE", ar: "بليز", isoen: 'GLOBAL', isoar: 'عالمي' },
    BJ: { en: "BENIN", ar: "بنين", isoen: 'GLOBAL', isoar: 'عالمي' },
    BM: { en: "BERMUDA", ar: "برمودا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BT: { en: "BHUTAN", ar: "بوتان", isoen: 'GLOBAL', isoar: 'عالمي' },
    BO: { en: "BOLIVIA", ar: "بوليفيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BA: { en: "BOSNIA AND HERZEGOVINA", ar: "البوسنة والهرسك", isoen: 'GLOBAL', isoar: 'عالمي' },
    BW: { en: "BOTSWANA", ar: "بوتسوانا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BG: { en: "BULGARIA", ar: "بلغاريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    BF: { en: "BURKINA FASO", ar: "بوركينا فاسو", isoen: 'GLOBAL', isoar: 'عالمي' },
    BI: { en: "BURUNDI", ar: "بوروندي", isoen: 'GLOBAL', isoar: 'عالمي' },
    KH: { en: "CAMBODIA", ar: "كمبوديا", isoen: 'GLOBAL', isoar: 'عالمي' },
    CM: { en: "CAMEROON", ar: "الكاميرون", isoen: 'GLOBAL', isoar: 'عالمي' },
    CV: { en: "CAPE VERDE ISLANDS", ar: "جزر الرأس الأخضر", isoen: 'GLOBAL', isoar: 'عالمي' },
    TD: { en: "CHAD", ar: "تشاد", isoen: 'GLOBAL', isoar: 'عالمي' },
    CL: { en: "CHILE", ar: "شيلي", isoen: 'GLOBAL', isoar: 'عالمي' },
    CG: { en: "CONGO", ar: "الكونغو", isoen: 'GLOBAL', isoar: 'عالمي' },
    CR: { en: "COSTA RICA", ar: "كوستا ريكا", isoen: 'GLOBAL', isoar: 'عالمي' },
    HR: { en: "CROATIA", ar: "كرواتيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    CY: { en: "CYPRUS", ar: "قبرص", isoen: 'GLOBAL', isoar: 'عالمي' },
    CZ: { en: "CZECH REPUBLIC", ar: "الجمهورية التشيكية", isoen: 'GLOBAL', isoar: 'عالمي' },
    DK: { en: "DENMARK", ar: "الدنمارك", isoen: 'GLOBAL', isoar: 'عالمي' },
    DJ: { en: "DJIBOUTI", ar: "جيبوتي", isoen: 'GLOBAL', isoar: 'عالمي' },
    DM: { en: "DOMINICA", ar: "دومينيكا", isoen: 'GLOBAL', isoar: 'عالمي' },
    EG: { en: "EGYPT", ar: "مصر", isoen: 'GLOBAL', isoar: 'عالمي' },
    ER: { en: "ERITREA", ar: "إريتريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    EE: { en: "ESTONIA", ar: "إستونيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    ET: { en: "ETHIOPIA", ar: "أثيوبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    FJ: { en: "FIJI", ar: "فيجي", isoen: 'GLOBAL', isoar: 'عالمي' },
    FI: { en: "FINLAND", ar: "فنلندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    PF: { en: "FRENCH POLYNESIA", ar: "بولينيزيا الفرنسية", isoen: 'GLOBAL', isoar: 'عالمي' },
    GA: { en: "GABON", ar: "جابون", isoen: 'GLOBAL', isoar: 'عالمي' },
    GM: { en: "GAMBIA", ar: "غامبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GE: { en: "GEORGIA", ar: "جورجيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GH: { en: "GHANA", ar: "غانا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GR: { en: "GREECE", ar: "اليونان", isoen: 'GLOBAL', isoar: 'عالمي' },
    GD: { en: "GRENADA", ar: "غرينادا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GN: { en: "GUINEA", ar: "غينيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    GY: { en: "GUYANA", ar: "غيانا", isoen: 'GLOBAL', isoar: 'عالمي' },
    HU: { en: "HUNGARY", ar: "هنغاريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    IS: { en: "ICELAND", ar: "أيسلندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    ID: { en: "INDONESIA", ar: "إندونيسيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    IR: { en: "IRAN", ar: "إيران", isoen: 'GLOBAL', isoar: 'عالمي' },
    IQ: { en: "IRAQ", ar: "العراق", isoen: 'GLOBAL', isoar: 'عالمي' },
    JM: { en: "JAMAICA", ar: "جامايكا", isoen: 'GLOBAL', isoar: 'عالمي' },
    JO: { en: "JORDAN", ar: "الأردن", isoen: 'GLOBAL', isoar: 'عالمي' },
    KZ: { en: "KAZAKHSTAN", ar: "كازاخستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    KE: { en: "KENYA", ar: "كينيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    KP: { en: "KOREA", ar: "كوريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    KW: { en: "KUWAIT", ar: "الكويت", isoen: 'GLOBAL', isoar: 'عالمي' },
    LV: { en: "LATVIA", ar: "لاتفيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    LB: { en: "LEBANON", ar: "لبنان", isoen: 'GLOBAL', isoar: 'عالمي' },
    LR: { en: "LIBERIA", ar: "ليبيريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    LY: { en: "LIBYA", ar: "ليبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    LT: { en: "LITHUANIA", ar: "ليثوانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    LU: { en: "LUXEMBOURG", ar: "لوكسمبورغ", isoen: 'GLOBAL', isoar: 'عالمي' },
    MG: { en: "MADAGASCAR", ar: "مدغشقر", isoen: 'GLOBAL', isoar: 'عالمي' },
    MW: { en: "MALAWI", ar: "ملاوي", isoen: 'GLOBAL', isoar: 'عالمي' },
    MY: { en: "MALAYSIA", ar: "ماليزيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    MV: { en: "MALDIVES", ar: "جزر المالديف", isoen: 'GLOBAL', isoar: 'عالمي' },
    ML: { en: "MALI", ar: "مالي", isoen: 'GLOBAL', isoar: 'عالمي' },
    MT: { en: "MALTA", ar: "مالطا", isoen: 'GLOBAL', isoar: 'عالمي' },
    MR: { en: "MAURITANIA", ar: "موريتانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    MU: { en: "MAURITIUS", ar: "موريشيوس", isoen: 'GLOBAL', isoar: 'عالمي' },
    MC: { en: "MONACO", ar: "موناكو", isoen: 'GLOBAL', isoar: 'عالمي' },
    MN: { en: "MONGOLIA", ar: "منغوليا", isoen: 'GLOBAL', isoar: 'عالمي' },
    ME: { en: "MONTENEGRO", ar: "مونتينيغرو", isoen: 'GLOBAL', isoar: 'عالمي' },
    MA: { en: "MOROCCO", ar: "المغرب", isoen: 'GLOBAL', isoar: 'عالمي' },
    MZ: { en: "MOZAMBIQUE", ar: "موزامبيق", isoen: 'GLOBAL', isoar: 'عالمي' },
    NA: { en: "NAMIBIA", ar: "ناميبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    NP: { en: "NEPAL", ar: "النيبال", isoen: 'GLOBAL', isoar: 'عالمي' },
    NZ: { en: "NEW ZEALAND", ar: "نيوزيلندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    NI: { en: "NICARAGUA", ar: "نيكاراغوا", isoen: 'GLOBAL', isoar: 'عالمي' },
    NE: { en: "NIGER", ar: "النيجر", isoen: 'GLOBAL', isoar: 'عالمي' },
    NG: { en: "NIGERIA", ar: "نيجيريا", isoen: 'GLOBAL', isoar: 'عالمي' },
    NO: { en: "NORWAY", ar: "النرويج", isoen: 'GLOBAL', isoar: 'عالمي' },
    OM: { en: "Oman", ar: "سلطنة عمان", isoen: 'OMN', isoar: 'عمان' },
    PK: { en: "PAKISTAN", ar: "باكستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    PA: { en: "PANAMA", ar: "بنما", isoen: 'GLOBAL', isoar: 'عالمي' },
    PG: { en: "PAPUA NEW GUINEA", ar: "بابوا غينيا الجديدة", isoen: 'GLOBAL', isoar: 'عالمي' },
    PY: { en: "PARAGUAY", ar: "باراغواي", isoen: 'GLOBAL', isoar: 'عالمي' },
    PE: { en: "PERU", ar: "بيرو", isoen: 'GLOBAL', isoar: 'عالمي' },
    PL: { en: "POLAND", ar: "بولندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    PT: { en: "PORTUGAL", ar: "البرتغال", isoen: 'GLOBAL', isoar: 'عالمي' },
    QA: { en: "Qatar", ar: "دولة قطر", isoen: 'QAT', isoar: 'قطر' },
    RO: { en: "ROMANIA", ar: "رومانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    RW: { en: "RWANDA", ar: "رواندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SA: { en: "Kingdom of Saudi Arabia", ar: "المملكة العربية السعودية", isoen: 'KSA', isoar: 'السعودية' },
    SN: { en: "SENEGAL", ar: "السنغال", isoen: 'GLOBAL', isoar: 'عالمي' },
    RS: { en: "SERBIA", ar: "صربيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SL: { en: "SIERRA LEONE", ar: "سيرا ليون", isoen: 'GLOBAL', isoar: 'عالمي' },
    SG: { en: "SINGAPORE", ar: "سنغافورة", isoen: 'GLOBAL', isoar: 'عالمي' },
    SK: { en: "SLOVAKIA", ar: "سلوفاكيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SI: { en: "SLOVENIA", ar: "سلوفينيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SB: { en: "SOLOMON ISLANDS", ar: "جزر سليمان", isoen: 'GLOBAL', isoar: 'عالمي' },
    SO: { en: "SOMALIA", ar: "الصومال", isoen: 'GLOBAL', isoar: 'عالمي' },
    ZA: { en: "SOUTH AFRICA", ar: "جنوب أفريقيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    LK: { en: "SRI LANKA", ar: "سيريلانكا", isoen: 'GLOBAL', isoar: 'عالمي' },
    SD: { en: "SUDAN", ar: "السودان", isoen: 'GLOBAL', isoar: 'عالمي' },
    SR: { en: "SURINAME", ar: "سورينام", isoen: 'GLOBAL', isoar: 'عالمي' },
    SZ: { en: "SWAZILAND", ar: "سوازيلاند", isoen: 'GLOBAL', isoar: 'عالمي' },
    TJ: { en: "TAJIKISTAN", ar: "طاجيكستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    TH: { en: "THAILAND", ar: "تايلاند", isoen: 'GLOBAL', isoar: 'عالمي' },
    TG: { en: "TOGO", ar: "توجو", isoen: 'GLOBAL', isoar: 'عالمي' },
    TT: { en: "TRINIDAD AND TOBAGO", ar: "ترينداد وتوباغو", isoen: 'GLOBAL', isoar: 'عالمي' },
    TN: { en: "TUNISIA", ar: "تونس", isoen: 'GLOBAL', isoar: 'عالمي' },
    TR: { en: "TURKEY", ar: "تركيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    TM: { en: "TURKMENISTAN", ar: "تركمانستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    TV: { en: "TUVALU", ar: "توفالو", isoen: 'GLOBAL', isoar: 'عالمي' },
    UG: { en: "UGANDA", ar: "أوغندا", isoen: 'GLOBAL', isoar: 'عالمي' },
    UA: { en: "UKRAINE", ar: "أوكرانيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    AE: { en: "United Arab Emirates", ar: "الإمارات العربية المتحدة", isoen: 'UAE', isoar: 'الإمارات' },
    US: { en: "United States of America", ar: "الولايات المتحدة", isoen: 'GLOBAL', isoar: 'عالمي' },
    UY: { en: "URUGUAY", ar: "أوروجواي", isoen: 'GLOBAL', isoar: 'عالمي' },
    UZ: { en: "UZBEKISTAN", ar: "أوزبيكستان", isoen: 'GLOBAL', isoar: 'عالمي' },
    VU: { en: "VANUATU", ar: "فانواتو", isoen: 'GLOBAL', isoar: 'عالمي' },
    YE: { en: "YEMEN", ar: "اليمن", isoen: 'GLOBAL', isoar: 'عالمي' },
    ZM: { en: "ZAMBIA", ar: "زامبيا", isoen: 'GLOBAL', isoar: 'عالمي' },
    RU: { en: 'RUSSIA', ar: 'روسيا', isoen: 'GLOBAL', isoar: 'عالمي' },
    XX: {
        en: "United States of America ",
        ar: "الولايات المتحدة الأمريكية ",
        isoen: 'GLOBAL',
        isoar: 'عالمي' 
    },
    get_inspired: { en: "Get inspired", ar: "تصفح التصاميم", isoen: 'GLOBAL', isoar: 'عالمي' },
    get_started: { en: "Get Started", ar: "ادخل موقعنا", isoen: 'GLOBAL', isoar: 'عالمي' }


}